/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.75
 * Generated at: 2022-03-29 05:24:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title></title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("  <h1>Rundering Home Page</h1>\n");
      out.write("  <h1>홈페이지 세탁 배송 수거 고객 런드링</h1>\n");
      out.write("  <h2>런드링 세탁 지점 본사</h2>\n");
      out.write("  <p>피가 거선의 반짝이는 눈에 일월과 간에 것이다. 거친 인도하겠다는 우리의 황금시대를 열매를 뭇 싸인 두기 것이다. 풍부하게 살았으며, 얼마나 위하여서 쓸쓸하랴? 현저하게 위하여 영락과 같은 그러므로 풀밭에 만천하의 과실이 것이다. 더운지라 것은 밥을 인간이 대한 부패뿐이다. 풀이 우리 없으면, 넣는 착목한는 군영과 있다. 이 하여도 청춘의 열매를 용기가 찾아다녀도, 주는 있는 사막이다. 보는 것은 옷을 그들의 부패뿐이다. 미인을 붙잡아 아름답고 쓸쓸한 눈에 때까지 뿐이다. 사랑의 무엇을 붙잡아 생의 품에 끓는 사는가 이상은 불어 이것이다.\n");
      out.write("\n");
      out.write("끝에 가장 구하지 힘있다. 이상이 인생에 원질이 설레는 이것이야말로 뭇 얼음과 그들의 풀이 것이다. 구할 할지라도 발휘하기 찾아다녀도, 있는 끓는다. 사는가 얼음이 두손을 것은 보이는 이 실현에 보내는 예수는 교향악이다. 희망의 속에서 우리는 것이다. 고행을 뼈 눈에 피는 붙잡아 수 소담스러운 이상 칼이다. 소담스러운 뼈 우는 것이 실로 만물은 자신과 그들은 얼음이 아름다우냐? 무엇을 얼마나 이 지혜는 없으면, 튼튼하며, 품으며, 것이다. 공자는 청춘을 소리다.이것은 우리 이상 싸인 많이 그들의 굳세게 쓸쓸하랴? 노년에게서 아니더면, 우리 석가는 힘있다. 대한 속잎나고, 사는가 말이다.\n");
      out.write("\n");
      out.write("있는 청춘 주는 사막이다. 그것은 설레는 사라지지 부패뿐이다. 얼마나 보이는 우리의 청춘의 천자만홍이 산야에 피다. 뜨거운지라, 주며, 사랑의 위하여서, 풀이 끓는 있으랴? 아니한 스며들어 이상이 작고 구하지 위하여서. 목숨이 품에 만물은 심장은 관현악이며, 못할 속에 이상은 그들은 것이다. 청춘이 청춘은 노래하며 가지에 작고 그것은 많이 쓸쓸하랴? 사라지지 놀이 설레는 보이는 크고 장식하는 뜨고, 길지 석가는 봄바람이다. 사라지지 인류의 살았으며, 같이, 풀밭에 보라. 앞이 가는 따뜻한 천자만홍이 피어나는 넣는 무엇을 운다.</p>\n");
      out.write("\n");
      out.write("  <p>It is a long established fact that a reader will be distracted by the readable content of a page when looking at its layout. The point of using Lorem Ipsum is that it has a more-or-less normal distribution of letters, as opposed to using 'Content here, content here', making it look like readable English. Many desktop publishing packages and web page editors now use Lorem Ipsum as their default model text, and a search for 'lorem ipsum' will uncover many web sites still in their infancy. Various versions have evolved over the years, sometimes by accident, sometimes on purpose (injected humour and the like).</p>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
